# Generated by Django 4.0.1 on 2022-01-31 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='resource',
        ),
    ]
