# Generated by Django 4.0.1 on 2022-01-31 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_board_options'),
        ('events', '0004_remove_event_duration_hours_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board', verbose_name='board'),
        ),
    ]
