# Generated by Django 4.0.1 on 2022-01-28 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'board'},
        ),
    ]
