# Generated by Django 4.0.1 on 2022-01-27 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0002_alter_resource_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Person'), (2, 'Equipment'), (3, 'Vehicle')], default=1, verbose_name='resource type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='display_name',
            field=models.TextField(db_index=True, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
